<?php
    include('connection.php');
    require_once 'Includes/Cezpdf.php';
    $pdf = new Cezpdf("LETTER","PORTRAIT");
    $pdf->selectFont('Includes/fonts/Calibri.afm');
    
    //get data post
    $reportTitle = $_POST['reportTitle'];
    $reportUser = $_POST['reportUser'];
    $reportType = $_POST['reportType'];
    $reportBranch = $_POST['branch'];
    $reportForumDate = $_POST['forumDate'];
    $reportSchedule = $_POST['schedule'];
    

    $h = $pdf->ez['pageHeight'];
    $w = $pdf->ez['pageWidth'];
    $fontSize = 11;
    $margin = $pdf->C2P(0.5);
    $row = $pdf->C2P(0.5);
    $hT = $h-$margin;
    $wT = $w-($margin*2);

    $dateTime = new DateTime();
    $dateTime->setTimezone(new DateTimeZone('Asia/Kuala_Lumpur'));
    $currentDate = $dateTime->format("F j, Y g:i A");
    
    $pdf->addInfo('Title',strtoupper($reportTitle));
    
    function generateData(){
        global $con, $reportUser, $reportType, $reportBranch, $reportForumDate, $reportSchedule;

        $sql = "SELECT * FROM members WHERE isregistered ='YES'";

        if($reportType == 1){
            $sql .= "AND user_s = '".$reportUser."'";
        }

        if(!empty($reportBranch)){
            $sql .= "AND branch ='".$reportBranch."'";
        }

        if(!empty($reportForumDate)){
            $sql .= "AND forum_date ='".$reportForumDate."'";
        }

        if(!empty($reportSchedule)){
            $sql .= "AND DATE_FORMAT(forum_day, '%p') = '".$reportSchedule."'";
        }
        
        $sql .= " ORDER BY branch";
        $result = $con->query($sql);
        $data = array();
        if ($result->num_rows > 0) {
            $data = $result->fetch_all(MYSQLI_ASSOC);
        }
        
        return $data;
    }

    function generateLine($t, $b, $w1, $h1, $w2, $h2){
        global $pdf;
        $extend = $pdf->C2P(0.013);
        $pdf->setLineStyle(1);

        if($t == 1){
            //top
            $pdf->line($w1-$extend,$h1,$w2+$extend,$h1);
        }
        
        //left corner
        $pdf->line($w1,$h1+$extend,$w1,$h2-$extend);
        
        //pb# or MemID divider
        $addW = $pdf->C2P(1.8);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);
        
        //Full Name divider
        $addW += $pdf->C2P(4.9);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);

        //Status divider
        $addW += $pdf->C2P(1.8);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);

        //Branch divider
        $addW += $pdf->C2P(3.9);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);

        //Incentive divider
        $addW += $pdf->C2P(1.4);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);
        
        //Forum Date divider
        $addW += $pdf->C2P(2.2);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);

        //Forum Attended divider
        $addW += $pdf->C2P(1.5);
        $pdf->line($w1+$addW,$h1+$extend,$w1+$addW,$h2-$extend);
        
        //right corner
        $pdf->line($w2,$h1+$extend,$w2,$h2-$extend);

        if($b == 1){
            //bottom
            $pdf->line($w1-$extend,$h2,$w2+$extend,$h2);
        }
    } 

    function displayHeader(){
        global $pdf, $margin, $hT, $wT, $fontSize, $row, $currentDate, $reportTitle, $reportUser;
        $pdf->addJpegFromFile('img/letterhead.jpg',$margin,$hT-$pdf->C2P(3.3),$wT,$pdf->C2P(3.5));
        $hT-=$row+$pdf->C2P(3.5);
        $pdf->addTextWrap($margin, $hT, $wT, $fontSize, "<b>OWNERSHIP FORUM REGISTRATION</b>",'center');    
        $hT-=$row;
        $pdf->addTextWrap($margin, $hT, $wT, $fontSize,"<b>".strtoupper($reportTitle)."</b>",'center');
        $hT-=$row;
        $pdf->addTextWrap($margin, $hT, $wT, $fontSize,"As of ". $currentDate,'center');
        $hT-=$row;
        $pdf->addTextWrap($margin, $hT, $wT, $fontSize,"Generated by: ". ucwords($reportUser),'center');
    }

    function registeredList(){
        global $pdf, $margin, $h, $hT, $wT, $fontSize, $row;
        $hT-=$row+$pdf->C2P(0.8);
        $startW = $margin*2;
        $fontSize = 11;

        $memberData = generateData();
        $totalRegistered = number_format(count($memberData));
        

        $pdf->addTextWrap($startW, $hT, $wT, $fontSize,"Total Registered:  " . "<b>".$totalRegistered."</b>",'left');
        $hT-=$row-$pdf->C2P(0.25);

        $defW = $startW;
        $defH = $hT;
        $fontSize = 9;
        $row = $margin;
        $hT-=$row;

        $pdf->addTextWrap($startW, $hT, $pdf->C2P(1.8), $fontSize,"<b>PB#/MemID</b>",'center');
        $startW+=$pdf->C2P(1.8);
        $pdf->addTextWrap($startW, $hT, $pdf->C2P(4.9), $fontSize,"<b>Full Name</b>",'center');
        $startW+=$pdf->C2P(4.9);
        $pdf->addTextWrap($startW, $hT, $pdf->C2P(1.8), $fontSize,"<b>Status</b>",'center');
        $startW+=$pdf->C2P(1.8);
        $pdf->addTextWrap($startW, $hT, $pdf->C2P(3.9), $fontSize,"<b>Branch</b>",'center');
        $startW+=$pdf->C2P(3.9);
        $pdf->addTextWrap($startW, $hT, $pdf->C2P(1.4), $fontSize,"<b>Incentive</b>",'center');
        $startW+=$pdf->C2P(1.4);
        $pdf->addTextWrap($startW, $hT, $pdf->C2P(2.2), $fontSize,"<b>Forum Date</b>",'center');
        $startW+=$pdf->C2P(2.2);
        
        $forumAttend = "<b>Forum Attended</b>";
        $forumAttend = $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.5), $fontSize,$forumAttend,'center');
        $tempH = $hT;
        while(!empty($forumAttend)){
            $hT-=$pdf->C2P(.3);
            $forumAttend = $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.5), $fontSize,$forumAttend,'center');
        }
        $startW+=$pdf->C2P(1.5);
        $pdf->addTextWrap($startW, $tempH, $pdf->C2P(2.1), $fontSize,"<b>Encoder</b>",'center');
        generateLine(1,1,$defW,$defH,$wT,$hT);

        foreach($memberData as $data){
            if($hT < 70){
                $pdf->ezNewPage();
                $hT = $h-$margin;
                $fontSize = 11;
                displayHeader();
                $hT-=$row+$pdf->C2P(0.8);
                $startW = $margin*2;
                $pdf->addTextWrap($startW, $hT, $wT, $fontSize,"Total Registered:  " . "<b>".$totalRegistered."</b>",'left');
                $hT-=$row-$pdf->C2P(0.25);

                $defW = $startW;
                $defH = $hT;
                $fontSize = 9;
                $row = $margin;
                $hT-=$row;

                $pdf->addTextWrap($startW, $hT, $pdf->C2P(1.8), $fontSize,"<b>PB#/MemID</b>",'center');
                $startW+=$pdf->C2P(1.8);
                $pdf->addTextWrap($startW, $hT, $pdf->C2P(4.9), $fontSize,"<b>Full Name</b>",'center');
                $startW+=$pdf->C2P(4.9);
                $pdf->addTextWrap($startW, $hT, $pdf->C2P(1.8), $fontSize,"<b>Status</b>",'center');
                $startW+=$pdf->C2P(1.8);
                $pdf->addTextWrap($startW, $hT, $pdf->C2P(3.9), $fontSize,"<b>Branch</b>",'center');
                $startW+=$pdf->C2P(3.9);
                $pdf->addTextWrap($startW, $hT, $pdf->C2P(1.4), $fontSize,"<b>Incentive</b>",'center');
                $startW+=$pdf->C2P(1.4);
                $pdf->addTextWrap($startW, $hT, $pdf->C2P(2.2), $fontSize,"<b>Forum Date</b>",'center');
                $startW+=$pdf->C2P(2.2);
                
                $forumAttend = "<b>Forum Attended</b>";
                $forumAttend = $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.5), $fontSize,$forumAttend,'center');
                $tempH = $hT;
                while(!empty($forumAttend)){
                    $hT-=$pdf->C2P(.3);
                    $forumAttend = $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.5), $fontSize,$forumAttend,'center');
                }
                $startW+=$pdf->C2P(1.5);
                $pdf->addTextWrap($startW, $tempH, $pdf->C2P(2.1), $fontSize,"<b>Encoder</b>",'center');
                generateLine(1,1,$defW,$defH,$wT,$hT);
            }
            
            //reset startW
            $startW = $defW;
            $defH = $hT;
            $hT-=$row;
            $lastH = array();
            $pdf->addTextWrap($startW+$pdf->C2P(0.1), $hT+$pdf->C2P(0.14), $pdf->C2P(1.8), $fontSize,$data['mem_id'],'left');
            $startW+=$pdf->C2P(1.8);

            $text = utf8_decode($data['fullname']);
            $text = $pdf->addTextWrap($startW+$pdf->C2P(0.1), $hT+$pdf->C2P(0.14), $pdf->C2P(4.9), $fontSize,$text,'left');
            $tempH = $hT;
            $lastH[0]= 0;
            while(!empty($text)){
                $hT-=$pdf->C2P(.3);
                $lastH[0]+=$pdf->C2P(.3);
                $text = $pdf->addTextWrap($startW+$pdf->C2P(0.1), $hT+$pdf->C2P(0.14), $pdf->C2P(4.9), $fontSize,$text,'left');
            }
            $hT = $tempH;
            $startW+=$pdf->C2P(4.9);

            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.8), $fontSize,$data['stat'],'center');
            $startW+=$pdf->C2P(1.8);

            $text = $data['branch'];
            $text = $pdf->addTextWrap($startW+$pdf->C2P(0.1), $hT+$pdf->C2P(0.14), $pdf->C2P(3.9), $fontSize,$text,'left');
            $tempH = $hT;
            $lastH[1]= 0;
            while(!empty($text)){
                $hT-=$pdf->C2P(.3);
                $lastH[1]+=$pdf->C2P(.3);
                $text = $pdf->addTextWrap($startW+$pdf->C2P(0.1), $hT+$pdf->C2P(0.14), $pdf->C2P(3.9), $fontSize,$text,'left');
            }
            $hT = $tempH;
            $startW+=$pdf->C2P(3.9);
            
            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.4), $fontSize,$data['incentive'],'center');
            $startW+=$pdf->C2P(1.4);
            
            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(2.2), $fontSize,$data['forum_date'] ." ". date("A",strtotime($data['forum_day'])),'center');
            $startW+=$pdf->C2P(2.2);

            $text = $data['forum_attended'];
            $text = $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.5), $fontSize,$text,'center');
            $tempH = $hT;
            $lastH[2]= 0;
            while(!empty($text)){
                $hT-=$pdf->C2P(.3);
                $lastH[2]+=$pdf->C2P(.3);
                $text = $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(1.5), $fontSize,$text,'center');
            }
            $hT = $tempH;
            $startW+=$pdf->C2P(1.5);

            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.14), $pdf->C2P(2.1), $fontSize,$data['user_s'],'center');
            $hT-=max($lastH);
            generateLine(0,1,$defW,$defH,$wT,$hT);
        }
    }

    function registeredTally(){
        global $pdf, $margin, $hT, $wT, $fontSize, $row, $con;
        $hT-=$row+$pdf->C2P(0.8);
        $startW = $margin*2;
        $fontSize = 11;
        $extend = $pdf->C2P(0.013);
        $defH = $hT;
        
        $memberData = generateData();
        $totalRecords = $totalRegistered = 0;
        $totalDay = array("day1" => 0, "day2" => 0, "day3" => 0);
        $memberRegData = array();
        $sql = "SELECT * FROM members";
        $result = $con->query($sql);
        if ($result->num_rows > 0) {
            $totalRecords = number_format(count($result->fetch_all(MYSQLI_ASSOC)));
        }
        $totalRegistered = number_format(count($memberData));
        
        foreach($memberData as $data){
            switch($data["forum_date"]){
                case "2024-02-03":
                    $totalDay["day1"]+=1;
                break;
                
                case "2024-02-04":
                    $totalDay["day2"]+=1;
                break;
                
                case "2024-02-05":
                    $totalDay["day3"]+=1;
                break;
            }
        
            $memberRegData[$data["branch"]][$data["forum_date"]][date("A",strtotime($data['forum_day'])) == "AM" ? "AM" : "PM"][] = $data["fullname"];
        }

        //top line for total table
        $pdf->line($startW-$extend,$defH,$wT+$extend,$defH);
        $hT-=$row;
        //left corner
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2));
        //right corner
        $pdf->line($wT,$defH+$extend,$wT,$hT-$extend-$pdf->C2P(0.2));
        //bottom
        $pdf->line($startW-$extend,$hT-$pdf->C2P(0.2),$wT+$extend,$hT-$pdf->C2P(0.2));

        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.02),$pdf->C2P(5.3), $fontSize,"<b>TOTAL RECORDS</b>",'center');
        $startW+=$pdf->C2P(5.3);
        //total records divider
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2));

        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.02),$pdf->C2P(5.3), $fontSize,"<b>TOTAL REGISTERED</b>",'center');
        $startW+=$pdf->C2P(5.3);
        //total registered divider
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2));

        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.02),$pdf->C2P(3), $fontSize,"<b>DAY 1 - FEB 3</b>",'center');
        $startW+=$pdf->C2P(3);
        //day 1 divider
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2));

        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.02),$pdf->C2P(3), $fontSize,"<b>DAY 2 - FEB 4</b>",'center');
        $startW+=$pdf->C2P(3);
        //day 2 divider
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2));

        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.02),$pdf->C2P(3), $fontSize,"<b>DAY 3 - FEB 5</b>",'center');
        $defH = $hT;
        $hT-=$row*2;
        $startW = $margin*2;
        //left corner
        $pdf->line($startW,$defH-$pdf->C2P(0.21),$startW,$hT-$extend-$pdf->C2P(0.2));
        //right corner
        $pdf->line($wT,$defH-$pdf->C2P(0.21),$wT,$hT-$extend-$pdf->C2P(0.2));
        //bottom
        $pdf->line($startW-$extend,$hT-$pdf->C2P(0.2),$wT+$extend,$hT-$pdf->C2P(0.2));
        
        $fontSize = 13;
        //total records data
        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.15),$pdf->C2P(5.3), $fontSize,"<b>".$totalRecords."</b>",'center');
        $startW+=$pdf->C2P(5.3);
        //total records divider
        $pdf->line($startW,$defH-$pdf->C2P(0.21),$startW,$hT-$extend-$pdf->C2P(0.2));

        //total registered data
        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.15),$pdf->C2P(5.3), $fontSize,"<b>".$totalRegistered."</b>",'center');
        $startW+=$pdf->C2P(5.3);
        //total registered divider
        $pdf->line($startW,$defH-$pdf->C2P(0.21),$startW,$hT-$extend-$pdf->C2P(0.2));

        //total day1 data
        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.15),$pdf->C2P(3), $fontSize,"<b>".$totalDay['day1']."</b>",'center');
        $startW+=$pdf->C2P(3);
        //total day1 divider
        $pdf->line($startW,$defH-$pdf->C2P(0.21),$startW,$hT-$extend-$pdf->C2P(0.2));

        //total day2 data
        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.15),$pdf->C2P(3), $fontSize,"<b>".$totalDay['day2']."</b>",'center');
        $startW+=$pdf->C2P(3);
        //total day2 divider
        $pdf->line($startW,$defH-$pdf->C2P(0.21),$startW,$hT-$extend-$pdf->C2P(0.2));

        //total day3 data
        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.15),$pdf->C2P(3), $fontSize,"<b>".$totalDay['day3']."</b>",'center');

        //breakdown table
        $hT-=$row*2;
        $defH = $hT;
        $startW = $margin*2;
        $fontSize = 11;
        //top line for breakdown table
        $pdf->line($startW-$extend,$defH,$wT+$extend,$defH);
        $hT-=$row;
        //left corner
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2)-$row);
        //right corner
        $pdf->line($wT,$defH+$extend,$wT,$hT-$extend-$pdf->C2P(0.2)-$row);
        //bottom
        $pdf->line($startW-$extend+$pdf->C2P(6),$hT-$pdf->C2P(0.1),$wT-$pdf->C2P(3.09),$hT-$pdf->C2P(0.1));
         
        //branch label
        $pdf->addTextWrap($startW, $hT-$pdf->C2P(0.25),$pdf->C2P(6), $fontSize,"<b>BRANCH</b>",'center');
        $startW+=$pdf->C2P(6);
        //branch label divider
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.2)-$row);

        //forumday breakdown
        $dayLabel = [
            "day1" => "<b>DAY 1 - FEB 3</b>",
            "day2" => "<b>DAY 2 - FEB 4</b>",
            "day3" => "<b>DAY 3 - FEB 5</b>",
        ];
        foreach($dayLabel as $label){
            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.06),$pdf->C2P(3.5), $fontSize,$label,'center');
            $startW+=$pdf->C2P(3.5);
            //for day divider
            $pdf->line($startW,$defH+$extend,$startW,$hT-$extend-$pdf->C2P(0.1));
        }

        //total label
        $pdf->addTextWrap($startW, $hT-$pdf->C2P(0.25),$pdf->C2P(3.08), $fontSize,"<b>TOTAL</b>",'center');

        //2nd row breakdown table
        $hT-=$row;
        $startW = $margin*2;
        //bottom
        $pdf->line($startW-$extend,$hT-$pdf->C2P(0.2),$wT+$extend,$hT-$pdf->C2P(0.2));

        //day AM and PM
        $daySched = array("<b>AM</b>","<b>PM</b>");
        $daySchedLabel = [
            "day1" => $daySched,
            "day2" => $daySched,
            "day3" => $daySched
        ];
        $startW+=$pdf->C2P(6);
        foreach($daySchedLabel as $schedLabel){
            foreach($schedLabel as $schedData){
                $pdf->addTextWrap($startW, $hT-$pdf->C2P(0.04),$pdf->C2P(1.75), $fontSize,$schedData,'center');
                $startW+=$pdf->C2P(1.75);
                //for sched divider
                $pdf->line($startW,$defH-$row-$pdf->C2P(0.1),$startW,$hT-$extend-$pdf->C2P(0.2));
            }
        }

        //breakdown table data
        $hT-=$pdf->C2P(0.2);
        $overallTotal = [
            "2024-02-03" => ["AM" => 0,"PM" => 0],
            "2024-02-04" => ["AM" => 0,"PM" => 0],
            "2024-02-05" => ["AM" => 0,"PM" => 0],
        ];
        foreach($memberRegData as $keyBranch => $forumData){
            $defH = $hT;
            $hT-=(($row*2));
            $startW = $margin*2;        
            //left corner
            $pdf->line($startW,$defH,$startW,$hT-$extend);
            //right corner
            $pdf->line($wT,$defH,$wT,$hT-$extend);
            //bottom line
            $pdf->line($startW-$extend,$hT,$wT+$extend,$hT);

            //branch data
            $branchData = strtoupper($keyBranch != "MAIN OFFICE") ? strtoupper(str_replace("OFFICE","",$keyBranch)) : strtoupper($keyBranch);
            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.35),$pdf->C2P(6), $fontSize,"<b>".$branchData."</b>",'center');
            //branch label divider
            $startW+=$pdf->C2P(6);
            $pdf->line($startW,$defH+$extend,$startW,$hT-$extend);

            //generate divider for forum day AM and PM
            foreach($daySchedLabel as $schedLabel){
                foreach($schedLabel as $schedData){
                    $startW+=$pdf->C2P(1.75);
                    //for sched divider
                    $pdf->line($startW,$defH,$startW,$hT-$extend);
                }
            }
            
            $startW-=$pdf->C2P(10.5);
            $forumSchedArray = [
                "2024-02-03" => ["AM","PM"],
                "2024-02-04" => ["AM","PM"],
                "2024-02-05" => ["AM","PM"]
            ];
            $totalPerBranch = 0;

            foreach($forumSchedArray as $keyDay => $schedData){
                foreach($schedData as $keySched){
                    $totalTally = isset($forumData[$keyDay][$keySched]) ? number_format(count($forumData[$keyDay][$keySched])) : 0;

                    $totalPerBranch+=$totalTally;
                    $overallTotal[$keyDay][$keySched]+=$totalTally;
                    
                    $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.35),$pdf->C2P(1.75), $fontSize,"<b>".$totalTally."</b>",'center');
                    $startW+=$pdf->C2P(1.75);
                }
            }

            //Total per branch
            $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.35),$pdf->C2P(3.08), $fontSize,"<b>".number_format($totalPerBranch)."</b>",'center');
        }

        //overall Total
        $defH = $hT;
        $hT-=(($row*2));
        $startW = $margin*2;      
        $pdf->setColor(0.70,0.00,0.00);

        //left corner
        $pdf->line($startW,$defH,$startW,$hT-$extend);
        //right corner
        $pdf->line($wT,$defH,$wT,$hT-$extend);
        //bottom line
        $pdf->line($startW-$extend,$hT,$wT+$extend,$hT);
        //branch label divider
        $startW+=$pdf->C2P(6);
        $pdf->line($startW,$defH+$extend,$startW,$hT-$extend);

        //generate divider for forum day AM and PM
        foreach($daySchedLabel as $schedLabel){
            foreach($schedLabel as $schedData){
                $startW+=$pdf->C2P(1.75);
                //for sched divider
                $pdf->line($startW,$defH,$startW,$hT-$extend);
            }
        }

        $startW-=$pdf->C2P(10.5);
        $finalTotal = 0;
        foreach($forumSchedArray as $keyDay => $schedData){
            foreach($schedData as $keySched){
                $schedFinalTotal = number_format($overallTotal[$keyDay][$keySched]);
                $finalTotal+=$schedFinalTotal;
                $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.35),$pdf->C2P(1.75), $fontSize,"<b>".$schedFinalTotal."</b>",'center');
                $startW+=$pdf->C2P(1.75);
            }
        }
        $pdf->addTextWrap($startW, $hT+$pdf->C2P(0.35),$pdf->C2P(3.08), $fontSize,"<b>".number_format($finalTotal)."</b>",'center');
    }

    displayHeader();

    if($reportType != 3){
        registeredList();
    }else{
        registeredTally();
    }

    $pdf->ezStream();
?>